# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       # Add build and test steps here.
#       - name: Install Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14

#       - name: Install Dependencies
#         run: npm install

#       - name: Build Application
#         run: npm run build

#       - name: Run Tests
#         run: npm test
#       - name: Deploy to Firebase
#         run: |
#                 firebase use: ${{ secrets.FIREBASE_PROJECT_ID }}

#                 firebase deploy: --token "${{ secrets.FIREBASE_TOKEN }}"
